[package]
name = "single_frame_mode"
version = "0.1.0"
authors = ["Emaad Paracha <emaad@emaadparacha.com>"]
edition = "2018"


[dependencies.qrusthy]
path = "../../"

[dependencies]
fitsio = "0.19.0"
